name: Build and Push Docker Images to ECR

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Configure AWS credentials using OIDC
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::539935451710:role/OIDC-Pavithra
        aws-region: us-east-1

    # Log in to Amazon ECR
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 539935451710.dkr.ecr.us-east-1.amazonaws.com

    # Create ECR repository for OpenProject if it doesn't exist
    - name: Create ECR repository for OpenProject
      run: |
        aws ecr describe-repositories --repository-names openproject --region us-east-1 || \
        aws ecr create-repository --repository-name openproject --region us-east-1

    # Build, tag, and push Docker image for OpenProject
    - name: Build, Tag & Push Docker Image for OpenProject
      run: |
        docker build -t openproject:latest -f Dockerfile .
        docker tag openproject:latest 539935451710.dkr.ecr.us-east-1.amazonaws.com/openproject:latest
        docker push 539935451710.dkr.ecr.us-east-1.amazonaws.com/openproject:latest

    # Optionally, remove local Docker images after pushing
    - name: Cleanup local Docker images
      run: |
        docker rmi 539935451710.dkr.ecr.us-east-1.amazonaws.com/openproject:latest
